import fs from 'fs';
import path from 'path';
import type {
  InvoicePaymentProofSummary,
  PaymentMethod,
  PaymentProofResponse,
  PaymentProofStatus,
} from '@apartment/shared';

/**
 * Legacy on-disk screenshot location.
 *
 * Proofs now store a Cloudinary public id (ADR 002). This directory is only read
 * to keep serving screenshots submitted before that move; nothing writes here
 * anymore.
 */
export const PAYMENT_PROOF_UPLOAD_DIR = path.join(
  __dirname,
  '..',
  '..',
  'uploads',
  'payment-proofs'
);

// ─────────────────────────────────────────────────────────────────────────────
// Manual payment proofs (ADR 008)
//
// Shared between the resident submission route (routes/invoices.ts) and the
// admin review routes (routes/payment-proofs.ts) so the two never drift on what
// a proof looks like, how the outstanding amount is computed, or where the
// screenshot is served from.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * The only URL clients ever see for a screenshot. It is access-controlled
 * (admins of the society, or the resident who submitted it) - the raw filename
 * in `PaymentProof.screenshotUrl` is never exposed, because this is financial
 * evidence rather than a ticket photo.
 */
export function proofScreenshotUrl(proofId: string): string {
  return `/api/v1/payment-proofs/${proofId}/screenshot`;
}

/**
 * Distinguish a pre-Cloudinary stored filename from a Cloudinary public id.
 * Public ids are `/`-separated (`omnihome/.../proof-...`); the files we wrote
 * locally were sanitized to this charset and never contain a slash.
 */
export function isLegacyLocalScreenshot(stored: string): boolean {
  return !stored.includes('/');
}

/** Minimal invoice shape a proof needs for review context. */
export interface ProofInvoice {
  id: string;
  invoiceNumber: string;
  title: string;
  amount: number;
  status: string;
  unitId: string;
  unit?: { unitNumber: string } | null;
  payments: { amount: number; status: string; paymentProofId?: string | null }[];
}

/** Minimal proof shape (with relations) the formatters below understand. */
export interface ProofRecord {
  id: string;
  societyId: string;
  invoiceId: string;
  residentId: string;
  claimedAmount: number;
  paymentMethod: string;
  transactionReference: string | null;
  status: string;
  reviewedById: string | null;
  reviewedAt: Date | null;
  rejectionReason: string | null;
  createdAt: Date;
  updatedAt: Date;
  resident?: { name: string } | null;
  reviewedBy?: { name: string } | null;
  invoice: ProofInvoice;
}

/**
 * What the invoice still asks for: its amount minus every succeeded payment,
 * EXCLUDING the payment generated by this proof itself. Excluding it matters
 * after an approval - once this proof's payment has landed the invoice is paid,
 * and without the exclusion a correct proof would suddenly look mismatched.
 *
 * Compare the result against `claimedAmount` to flag a mismatch; the proof's
 * amount is never adjusted to fit (no partial payments in this model).
 */
export function outstandingAmount(invoice: ProofInvoice, excludeProofId?: string): number {
  const paid = invoice.payments
    .filter((p) => p.status === 'succeeded' && p.paymentProofId !== excludeProofId)
    .reduce((sum, p) => sum + p.amount, 0);
  return Math.max(invoice.amount - paid, 0);
}

/** Does the claimed amount differ from what the invoice still asks for? */
export function hasAmountMismatch(proof: ProofRecord): boolean {
  return proof.claimedAmount !== outstandingAmount(proof.invoice, proof.id);
}

/** The compact proof summary embedded in an invoice response (resident view). */
export function formatProofSummary(proof: ProofRecord): InvoicePaymentProofSummary {
  return {
    id: proof.id,
    status: proof.status as PaymentProofStatus,
    claimedAmount: proof.claimedAmount,
    paymentMethod: proof.paymentMethod as PaymentMethod,
    transactionReference: proof.transactionReference ?? null,
    screenshotUrl: proofScreenshotUrl(proof.id),
    rejectionReason: proof.rejectionReason ?? null,
    reviewedByName: proof.reviewedBy?.name ?? null,
    reviewedAt: proof.reviewedAt?.toISOString() ?? null,
    createdAt: proof.createdAt.toISOString(),
  };
}

/** The full proof record shown in the admin review queue. */
export function formatPaymentProof(proof: ProofRecord): PaymentProofResponse {
  return {
    ...formatProofSummary(proof),
    societyId: proof.societyId,
    invoiceId: proof.invoiceId,
    invoiceNumber: proof.invoice.invoiceNumber,
    invoiceTitle: proof.invoice.title,
    invoiceOutstandingAmount: outstandingAmount(proof.invoice, proof.id),
    invoiceStatus: proof.invoice.status as PaymentProofResponse['invoiceStatus'],
    unitId: proof.invoice.unitId,
    unitNumber: proof.invoice.unit?.unitNumber ?? '',
    residentId: proof.residentId,
    residentName: proof.resident?.name ?? 'Unknown',
    reviewedById: proof.reviewedById ?? null,
    amountMismatch: hasAmountMismatch(proof),
    updatedAt: proof.updatedAt.toISOString(),
  };
}

/** Prisma include that produces exactly the shape the formatters expect. */
export const paymentProofInclude = {
  resident: { select: { name: true } },
  reviewedBy: { select: { name: true } },
  invoice: {
    select: {
      id: true,
      invoiceNumber: true,
      title: true,
      amount: true,
      status: true,
      unitId: true,
      unit: { select: { unitNumber: true } },
      payments: { select: { amount: true, status: true, paymentProofId: true } },
    },
  },
} as const;
